### PR TITLE
remove italian locale, so keep I18n.available_locales in sync with app locales

### PR DESCRIPTION
**Pull request by marcusg**

### CODE REVIEW

**Comment by stefanoverna** [comment]
Hi @marcusg, I'm not sure how the it.yml file interferes with I18n.available_locales

**Comment by marcusg** [comment]
hi @stefanoverna, the locale is loaded in my application (a simple active_admin app with globalize3 and your activeadmin-globalize3 gem). I don't need italian translations, but with the use of activeadmin-globalize3 it came into my I18n.available_locales, as it is loaded. Maybe I'm doing it wrong, but removing the it.yml solves the problem for me :)

**Comment by joanamartins** [comment]
@marcusg rather than removing the file, wouldn't it be better to set the available locales for your application in the configuration?

For example, in `config/application.rb:`

``` ruby
class Application < Rails::Application
  ...
  config.i18n.available_locales = [ :en, "pt-PT" ]
  config.i18n.default_locale = "pt-PT"
  ...
end
```

This way, `I18n.available_locales` will return just the locales you want and the Italian (or any other) translation won't pollute it.

**Comment by marcusg** [comment]
@joanamartins: thanks, that could do the trick (have not tested it yet). So all of you think it is the better solution to hard-code the available_locales?

**Comment by nebirhos** [comment]
yep, it's the way to do it

**Comment by marcusg** [comment]
ok, thanks for the info!

**Pull request closed without merging**
